---

- set_fact:
    instances: "{{ instances | map('combine', {'public_key' : env_public_key}) | list }}"
  when: instances.public_key is not defined

- set_fact:
    instances: "{{ instances | map('combine', {'private_key_path' : ssh_key_path}) | list }}"
  when: instances.private_key_path is not defined

- name: Create ravello cloud jinja template from vm instance definitions
  ravello_cloud_template:
    path: "{{ template_path }}.j2"
    instances: "{{ instances }}"

- name: Expand jinja template into finalized ravello template
  template:
    src: "{{ template_path }}.j2"
    dest: "{{ template_path }}"

- name: "build staging app based on {{ app_template }}"
  local_action:
    module: ravello_module
    app_name: "{{ application_name }}-tmp"
    description: "{{ application_name }}"
    app_template: "{{ template_path }}"
    state: design
  register: design_results


- name: publish application and wait for start
  local_action:
    module: ravello_module
    app_name: "{{ application_name }}"
    description: "{{ application_name }}"
    state: present
    blueprint_id: "{{ design_results.blueprint_id }}"
    wait_timeout: "{{ wait_timeout }}"
    application_ttl: "{{ env_expire }}"
    cost_bucket: "{{ ravello_cost_bucket }}"
    publish_optimization: "{{ publish_optimization }}"
    region: "{{ publish_region }}"
    cloud: "{{ publish_cloud }}"
  register: app_results

