---
- name: display variables for create application based on deployed blueprint and wait for start
  debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - application_name
    - application_description
    - blueprint_id
    - wait_timeout

- name: create application based on deployed blueprint and wait for start
  local_action:
    module: ravello_app
    name: "{{ application_name }}"
    description: "{{ application_description }}"
    state: present
    blueprint_id: "{{ blueprint_id }}"
    wait_timeout: "{{ wait_timeout }}"
  register: app_results

- debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
  - app_results.name
  - app_results.app_id

- name: delete blueprint used to create application
  local_action:
    blueprint_name: "{{ blueprint_name + '-bp' }}"
    name: "{{ app_results.name }}"
    module: ravello_app
    state: blueprint_delete
  register: bp_delete_results

- debug:
    var: bp_delete_results
    verbosity: 1
