---
- name: display variables for create blueprint based on app_template.yml
  debug:
    var: "{{ item }}"
    verbosity: 1
  with_items:
    - blueprint_name
    - blueprint_description

- name: create blueprint based on app_template.yml
  local_action:
    module: ravello_app
    name: "{{ blueprint_name }}"
    description: "{{ blueprint_description }}"
    app_template: 'app_template.yml'
    state: design
  register: design_results

- debug:
    var: design_results
    verbosity: 1
  with_items:
    - design_results.name
    - design_results.blueprint_id
