# vim: set ft=ansible:
---
- name: Force unregister before register
  redhat_subscription:
    state: absent
  register: task_result
  until: task_result | succeeded
  retries: 10
  delay: 5

- name: register node with subscription-manager
  redhat_subscription:
    state: present
    activationkey: "{{ activationkey }}"
    org_id: "{{ org }}"
    pool: "{{ rhn_pool_id_string }}"
    auto_attach: yes
  register: task_result
  until: task_result | succeeded
  retries: "{{ register_node_retries }}"
  delay: 5

- name: enable repos for rhel
  command: subscription-manager repos --enable "{{ item }}"
  with_items:
    - '{{ repos_to_enable }}'
  retries: 10
  delay: 5
