repos_to_enable:
  - rhel-7-server-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-ose-3.9-rpms
  - rhel-7-fast-datapath-rpms
  - rhel-7-server-ansible-2.4-rpms

common_packages:
   - python
   - bind
   - git
   - net-tools
   - iptables-services
   - bridge-utils
   - kexec-tools
   - sos
   - haproxy
   - psacct
   - unzip
   - bash-completion
   - tmux
   - bind-utils
   - wget
   - ansible
   - git
   - vim-enhanced

openshift_packages:
   - atomic-openshift-utils
   - atomic-openshift-clients
