---
# tasks file for reboot-host
#

- name: wait for remote connection release if current host is proxy
  pause:
    seconds: 15
  when: (hostIsProxy is defined) and (hostIsProxy)

- name: send reboot request to systemd
  become: true
  shell: /usr/bin/systemd-run --on-active=10 /usr/bin/systemctl reboot

- name: wait for proxy host availability
  remote_user: "{{ ansible_user }}"
  local_action:
    module: wait_for
    port: 22
    host: "{{ proxyFqdn }}"
    search_regex: OpenSSH
    delay: 30
  when: proxyFqdn is defined

- name: wait for host availability (from localhost)
  remote_user: "{{ ansible_user }}"
  local_action:
    module: wait_for
    port: 22
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    delay: 30
  when: proxyFqdn is not defined

- name: wait for host availibity (delegate to proxy)
  wait_for:
    port: 22
    host: "{{ inventory_hostname }}"
    search_regex: OpenSSH
    delay: 30
  delegate_to: "{{ proxyFqdn }}"
  when: proxyFqdn is defined

